// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh60Td6tnWrWasaMypxqvkWUb4gTkcRcY',
    appId: '1:772216443701:android:af531915c577daac82327c',
    messagingSenderId: '772216443701',
    projectId: 'food-ninja-eff0d',
    storageBucket: 'food-ninja-eff0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9WCHhMG4TO3Gw3vI5QD5hNnUJ06HZQBQ',
    appId: '1:772216443701:ios:b28b75a3204b97d782327c',
    messagingSenderId: '772216443701',
    projectId: 'food-ninja-eff0d',
    storageBucket: 'food-ninja-eff0d.appspot.com',
    androidClientId: '772216443701-9laonib5l9rqvle9nkcvg4uv2j80r9bd.apps.googleusercontent.com',
    iosClientId: '772216443701-0nu3hq0q3o9gfnpvu543ijpj30s5scnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodNinja',
  );
}
